/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto01;

/**
 *
 * @author thoma
 */
public class ViewBuses extends javax.swing.JFrame {

    
    Buses[] listaBuses;
    int contador;
    public ViewBuses() {
        initComponents();
        //Se inicializa el arrelo
        listaBuses = new Buses[10];
        //Se inicializa el cotador 
        contador = 0;
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnOpcion2 = new javax.swing.JButton();
        jrbOpcion1 = new javax.swing.JRadioButton();
        jrbOpcion2 = new javax.swing.JRadioButton();
        jrbOpcion3 = new javax.swing.JRadioButton();
        BtnGuardarBus = new javax.swing.JButton();
        btnOpcion3 = new javax.swing.JButton();
        btnOpcion1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(73, 181, 172));
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto01/img/Logo.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 362, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 480));

        jPanel2.setBackground(new java.awt.Color(33, 45, 62));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Distrubucion y Cantidad De Sillas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Placa");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        txtPlaca.setBackground(new java.awt.Color(33, 45, 62));
        txtPlaca.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtPlaca.setForeground(new java.awt.Color(255, 255, 255));
        txtPlaca.setBorder(null);
        txtPlaca.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registra Tus Buses");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 150, 10));

        btnOpcion2.setBackground(new java.awt.Color(73, 181, 172));
        btnOpcion2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnOpcion2.setForeground(new java.awt.Color(255, 255, 255));
        btnOpcion2.setText("Visualizar");
        btnOpcion2.setBorder(null);
        btnOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 99, 34));

        jrbOpcion1.setBackground(new java.awt.Color(33, 45, 62));
        buttonGroup1.add(jrbOpcion1);
        jrbOpcion1.setText("MicroBus");
        jPanel2.add(jrbOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jrbOpcion2.setBackground(new java.awt.Color(33, 45, 62));
        buttonGroup1.add(jrbOpcion2);
        jrbOpcion2.setText("Buseta");
        jPanel2.add(jrbOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jrbOpcion3.setBackground(new java.awt.Color(33, 45, 62));
        buttonGroup1.add(jrbOpcion3);
        jrbOpcion3.setText("AutoBus");
        jPanel2.add(jrbOpcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        BtnGuardarBus.setBackground(new java.awt.Color(73, 181, 172));
        BtnGuardarBus.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        BtnGuardarBus.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardarBus.setText("GUARDAR");
        BtnGuardarBus.setBorder(null);
        BtnGuardarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarBusActionPerformed(evt);
            }
        });
        jPanel2.add(BtnGuardarBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 99, 34));

        btnOpcion3.setBackground(new java.awt.Color(73, 181, 172));
        btnOpcion3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnOpcion3.setForeground(new java.awt.Color(255, 255, 255));
        btnOpcion3.setText("Visualizar");
        btnOpcion3.setBorder(null);
        btnOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnOpcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 99, 34));

        btnOpcion1.setBackground(new java.awt.Color(73, 181, 172));
        btnOpcion1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnOpcion1.setForeground(new java.awt.Color(255, 255, 255));
        btnOpcion1.setText("Visualizar");
        btnOpcion1.setBorder(null);
        btnOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 99, 34));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 450, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion2ActionPerformed
       
    ViewOpcion1 open = new ViewOpcion1();
    open.setVisible(true);

    }//GEN-LAST:event_btnOpcion2ActionPerformed

    private void BtnGuardarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarBusActionPerformed
        
        if(contador < listaBuses.length){
           String placa = txtPlaca.getText();
           /*
           boolean distribucion1 = jrbOpcion1.isSelected();
           boolean distribucion2 = jrbOpcion2.isSelected();
           boolean distribucion3 = jrbOpcion3.isSelected();
           */
           if(jrbOpcion1.isSelected()==true){
                int dis1[][] = new int[2][5];
           }
           /*else if(jrbOpcion2.isSelected()==true){
               int dis2[][] = new int[2][8];
           }else if(jrbOpcion3.isSelected()==true){
               int dis3[][] = new int[2][10];
           }
           */
           //Se crea el objeto
            Buses objBuses = new Buses();
            
            objBuses.setPlaca(placa);
            //objBuses.setDistribucionSillas(dis1);         
       }
    }//GEN-LAST:event_BtnGuardarBusActionPerformed

    private void btnOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion3ActionPerformed
              
    ViewOpcion2 open = new ViewOpcion2();
    open.setVisible(true);

    }//GEN-LAST:event_btnOpcion3ActionPerformed

    private void btnOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion1ActionPerformed
              
    ViewOpcion3 open = new ViewOpcion3();
    open.setVisible(true);

    }//GEN-LAST:event_btnOpcion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBuses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardarBus;
    private javax.swing.JButton btnOpcion1;
    private javax.swing.JButton btnOpcion2;
    private javax.swing.JButton btnOpcion3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton jrbOpcion1;
    private javax.swing.JRadioButton jrbOpcion2;
    private javax.swing.JRadioButton jrbOpcion3;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
