/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto01;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author thoma
 */
public class ViewCompra extends javax.swing.JFrame {

    Compra[] listaCompra;

    int contador;

    public ViewCompra() {
        initComponents();

        listaCompra = new Compra[10];
        contador = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtbGuardarCompra = new javax.swing.JButton();
        rbtDebito = new javax.swing.JRadioButton();
        rbtCredito = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        btnVolverCompra = new javax.swing.JButton();
        rbtEfectivo = new javax.swing.JRadioButton();
        jDateCompra = new com.toedter.calendar.JDateChooser();
        SpinnerSillas = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(73, 181, 172));
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto01/img/Logo.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 362, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 390));

        jPanel2.setBackground(new java.awt.Color(33, 45, 62));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha De Salida");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione Su N° De Silla");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Realiza Tu Compra");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        BtbGuardarCompra.setBackground(new java.awt.Color(73, 181, 172));
        BtbGuardarCompra.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        BtbGuardarCompra.setForeground(new java.awt.Color(255, 255, 255));
        BtbGuardarCompra.setText("GUARDAR");
        BtbGuardarCompra.setBorder(null);
        BtbGuardarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtbGuardarCompraActionPerformed(evt);
            }
        });
        jPanel2.add(BtbGuardarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 90, 30));

        rbtDebito.setBackground(new java.awt.Color(33, 45, 62));
        buttonGroup1.add(rbtDebito);
        rbtDebito.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        rbtDebito.setForeground(new java.awt.Color(255, 255, 255));
        rbtDebito.setText("Tarjeta De Debito");
        rbtDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDebitoActionPerformed(evt);
            }
        });
        jPanel2.add(rbtDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        rbtCredito.setBackground(new java.awt.Color(33, 45, 62));
        buttonGroup1.add(rbtCredito);
        rbtCredito.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        rbtCredito.setForeground(new java.awt.Color(255, 255, 255));
        rbtCredito.setText("Tarjeta De Credito");
        jPanel2.add(rbtCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Seleccione Su Metodo De Pago Modo De Pago");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        btnVolverCompra.setBackground(new java.awt.Color(73, 181, 172));
        btnVolverCompra.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnVolverCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverCompra.setText("x");
        btnVolverCompra.setBorder(null);
        btnVolverCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverCompraActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolverCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 0, 30, 30));

        rbtEfectivo.setBackground(new java.awt.Color(33, 45, 62));
        buttonGroup1.add(rbtEfectivo);
        rbtEfectivo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        rbtEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        rbtEfectivo.setText("Efectivo");
        jPanel2.add(rbtEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jDateCompra.setBackground(new java.awt.Color(33, 45, 62));
        jDateCompra.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.add(jDateCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, -1));
        jPanel2.add(SpinnerSillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 550, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtbGuardarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtbGuardarCompraActionPerformed
        Date fecha = new Date();
        if (contador < listaCompra.length) {
            Date fechaIda = jDateCompra.getDate();
            int sillas = Integer.parseInt(SpinnerSillas.getValue().toString());
            String seleccionPago = "";
            Date fechaCompra = fecha;

            if (rbtEfectivo.isSelected()) {
                seleccionPago = rbtEfectivo.getText();
            } else if (rbtDebito.isSelected()) {
                seleccionPago = rbtDebito.getText();
            } else {
                seleccionPago = rbtCredito.getText();
            }
            //Se crea el objeto
            Compra objCompra = new Compra(fechaIda, fechaCompra, sillas, seleccionPago);

            listaCompra[contador] = objCompra;
            contador++;

            JOptionPane.showMessageDialog(this, "Se Ha Realizado La Compra Con Exito!!");
            JOptionPane.showMessageDialog(this, "Por Favor Copie Este Recibo De Pago: \n" + "Fecha De Compra: " + objCompra.getFechaCompra()+ "\n" + "Su Silla es: " + objCompra.getnSilla() + "\n" + "Su Pago Se Realizo Con: " + objCompra.getPago()+ "\n"+"La Fecha De Salida Es: "+ objCompra.getFecha_ida());
        } else {
            JOptionPane.showMessageDialog(this, "Error Contacte Con El Administrador", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtbGuardarCompraActionPerformed

    private void btnVolverCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverCompraActionPerformed
        ViewCliente open = new ViewCliente();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverCompraActionPerformed

    private void rbtDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDebitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtDebitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtbGuardarCompra;
    private javax.swing.JSpinner SpinnerSillas;
    private javax.swing.JButton btnVolverCompra;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbtCredito;
    private javax.swing.JRadioButton rbtDebito;
    private javax.swing.JRadioButton rbtEfectivo;
    // End of variables declaration//GEN-END:variables
}
