/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto01;

import javax.swing.JOptionPane;

/**
 *
 * @author Thomas y Felipe
 */
public class ViewConductor extends javax.swing.JFrame {

    Conductor[] ListaConductores;
    int contador;

    /**
     * Creates new form ViewConductor
     */
    public ViewConductor() {
        initComponents();
        ListaConductores = new Conductor[5];
        contador = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoEmpresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        BtnBuscarConductor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        comboExperiencia = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtNumeroLicencia = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        BtnGuardarConductor = new javax.swing.JButton();
        BtnEliminarConductor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(73, 181, 172));
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 470));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto01/img/Logo.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 520));

        jPanel2.setBackground(new java.awt.Color(33, 45, 62));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cedula");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 112, -1, -1));

        txtCedula.setBackground(new java.awt.Color(33, 45, 62));
        txtCedula.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(255, 255, 255));
        txtCedula.setBorder(null);
        txtCedula.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 182, -1, -1));

        txtNombre.setBackground(new java.awt.Color(33, 45, 62));
        txtNombre.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        txtNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 150, 20));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        txtCodigoEmpresa.setBackground(new java.awt.Color(33, 45, 62));
        txtCodigoEmpresa.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtCodigoEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoEmpresa.setBorder(null);
        txtCodigoEmpresa.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtCodigoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 150, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Codigo Empresa");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(33, 45, 62));
        txtTelefono.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setBorder(null);
        txtTelefono.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 150, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Conductor");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 164, 150, 7));

        jSeparator2.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 239, 150, 10));

        jSeparator3.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 150, 10));

        BtnBuscarConductor.setBackground(new java.awt.Color(73, 181, 172));
        BtnBuscarConductor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        BtnBuscarConductor.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarConductor.setText("BUSCAR");
        BtnBuscarConductor.setBorder(null);
        BtnBuscarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarConductorActionPerformed(evt);
            }
        });
        jPanel2.add(BtnBuscarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 99, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        txtApellido.setBackground(new java.awt.Color(33, 45, 62));
        txtApellido.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBorder(null);
        txtApellido.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 150, -1));

        jSeparator5.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 150, 10));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Direccion");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        txtDireccion.setBackground(new java.awt.Color(33, 45, 62));
        txtDireccion.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setBorder(null);
        txtDireccion.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 150, 30));

        jSeparator6.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 150, 10));

        jSeparator7.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 150, 10));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Experiencia");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        txtEmail.setBackground(new java.awt.Color(33, 45, 62));
        txtEmail.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 150, -1));

        jSeparator8.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 150, 10));

        comboExperiencia.setBackground(new java.awt.Color(33, 45, 62));
        comboExperiencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Año a 5 Años", "6 Años a 10 Años", "11 Años a 15 Años", "16 Años o Mas..." }));
        jPanel2.add(comboExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Numero De Licencia");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        txtNumeroLicencia.setBackground(new java.awt.Color(33, 45, 62));
        txtNumeroLicencia.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtNumeroLicencia.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroLicencia.setBorder(null);
        txtNumeroLicencia.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNumeroLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroLicenciaActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumeroLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 150, 30));

        jSeparator9.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 150, 10));

        BtnGuardarConductor.setBackground(new java.awt.Color(73, 181, 172));
        BtnGuardarConductor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        BtnGuardarConductor.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardarConductor.setText("GUARDAR");
        BtnGuardarConductor.setBorder(null);
        BtnGuardarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarConductorActionPerformed(evt);
            }
        });
        jPanel2.add(BtnGuardarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 99, 30));

        BtnEliminarConductor.setBackground(new java.awt.Color(73, 181, 172));
        BtnEliminarConductor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        BtnEliminarConductor.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarConductor.setText("ELIMINAR");
        BtnEliminarConductor.setBorder(null);
        BtnEliminarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarConductorActionPerformed(evt);
            }
        });
        jPanel2.add(BtnEliminarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 99, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -30, 650, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarConductorActionPerformed
         
    }//GEN-LAST:event_BtnBuscarConductorActionPerformed

    public void Limpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        comboExperiencia.setSelectedIndex(0);
        txtCedula.setText("");
        txtCodigoEmpresa.setText("");
        txtDireccion.setText("");
        txtEmail.setText("");
        txtNumeroLicencia.setText("");
        txtTelefono.setText("");
    }
    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtNumeroLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroLicenciaActionPerformed

    private void BtnGuardarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarConductorActionPerformed
        if (contador < ListaConductores.length) {
            String Cedula = txtCedula.getText();
            String Nombre = txtNombre.getText();
            String Apellido = txtApellido.getText();
            String Direccion = txtDireccion.getText();
            String Telefono = txtTelefono.getText();
            String Email = txtEmail.getText();
            String NumeroLicencia = txtDireccion.getText();
            String Experiencia = comboExperiencia.getSelectedItem().toString();
            String CodigoEmpresa = txtCodigoEmpresa.getText();

            Conductor objCon = new Conductor();
            
            objCon.setCedula(Cedula);
            objCon.setNombre(Nombre);            
            objCon.setApellido(Apellido);
            objCon.setDireccion(Direccion);
            objCon.setTelefono(Telefono);
            objCon.setEmail(Email);
            objCon.setNumeroLicencia(NumeroLicencia);
            objCon.setExperiencia(Experiencia);
            objCon.setCodigoEmpresa(CodigoEmpresa);
            
            ListaConductores[contador] = objCon;
            contador++;
            
            JOptionPane.showMessageDialog(this, "Van "+ contador+ " Conductores y Los datos fueron Capturados");
        }
        else{
            JOptionPane.showMessageDialog(this, "ERRROR LOS CONDUCTORES ESTAN COMPLETOS");
            
        }
        Limpiar();
    }//GEN-LAST:event_BtnGuardarConductorActionPerformed

    private void BtnEliminarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarConductorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConductor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConductor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConductor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConductor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarConductor;
    private javax.swing.JButton BtnEliminarConductor;
    private javax.swing.JButton BtnGuardarConductor;
    private javax.swing.JComboBox comboExperiencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigoEmpresa;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroLicencia;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
